using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using UnbelievaBoat.Net.Models;
using Xunit;
using FluentAssertions;
using System.Text.Json;
using UnbelievaBoat.Net;
using System.Collections.Generic;
using System.Linq;

public class ItemsEndpointsTests : IDisposable
{
    private const string DummyToken = "test_token";
    private const string DefaultTestBaseUrl = "http://localhost";
    private const string ApiPathPrefix = "/api/v1";
    private HttpClient _mockHttpClient;
    private MockHttpMessageHandler _mockHttpMessageHandler;

    private UnbelievaBoatClient CreateTestClient(MockHttpMessageHandler handler)
    {
        _mockHttpMessageHandler = handler;
        _mockHttpClient = new HttpClient(_mockHttpMessageHandler);
        return new UnbelievaBoatClient(DummyToken, $"{DefaultTestBaseUrl}{ApiPathPrefix}", httpClient: _mockHttpClient);
    }

    [Fact]
    public async Task GetStoreItemsAsync_ValidRequest_ReturnsListOfStoreItems()
    {
        var guildId = "guild1";
        var expectedItems = new List<StoreItem>
        {
            new StoreItem { Id = "item1", Name = "Test Item 1", Price = 100 },
            new StoreItem { Id = "item2", Name = "Test Item 2", Price = 200 }
        };
        var jsonResponse = JsonSerializer.Serialize(expectedItems, UnbelievaBoatClient.DefaultJsonSerializerOptions);

        var client = CreateTestClient(MockHttpMessageHandler.Create(HttpStatusCode.OK, jsonResponse, req =>
        {
            req.Method.Should().Be(HttpMethod.Get);
            req.RequestUri.AbsolutePath.Should().Be($"{ApiPathPrefix}/guilds/{guildId}/items");
        }));

        var result = await client.GetStoreItemsAsync(guildId);
        result.Should().BeEquivalentTo(expectedItems);
    }

    [Fact]
    public async Task CreateStoreItemAsync_ValidRequest_ReturnsCreatedStoreItem()
    {
        var guildId = "guild1";
        var newItem = new StoreItem { Name = "New Item", Price = 150, Description = "A cool new item" };
        // Simulate API response where ID and timestamps are generated by the server
        var expectedCreatedItem = newItem with { Id = "newItemId123", CreatedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow };
        var jsonResponse = JsonSerializer.Serialize(expectedCreatedItem, UnbelievaBoatClient.DefaultJsonSerializerOptions);

        StoreItem capturedPayload = null;

        var client = CreateTestClient(MockHttpMessageHandler.Create(HttpStatusCode.Created, jsonResponse, async req =>
        {
            req.Method.Should().Be(HttpMethod.Post);
            req.RequestUri.AbsolutePath.Should().Be($"{ApiPathPrefix}/guilds/{guildId}/items");
            var content = await req.Content.ReadAsStringAsync();
            capturedPayload = JsonSerializer.Deserialize<StoreItem>(content, UnbelievaBoatClient.DefaultJsonSerializerOptions);
        }));

        var result = await client.CreateStoreItemAsync(guildId, newItem);

        result.Should().BeEquivalentTo(expectedCreatedItem);
        // Ensure the payload sent to the server was what we intended, excluding server-generated fields
        capturedPayload.Should().BeEquivalentTo(newItem, options =>
            options.Excluding(si => si.Id)
                   .Excluding(si => si.CreatedAt)
                   .Excluding(si => si.UpdatedAt)
                   .Excluding(si => si.StockRemaining) // if not part of create DTO explicitly
        );
    }

    [Fact]
    public async Task DeleteStoreItemAsync_ValidRequest_SendsDeleteRequest()
    {
        var guildId = "guild1";
        var itemId = "itemToDelete";
        bool requestValidated = false;

        var client = CreateTestClient(MockHttpMessageHandler.Create(HttpStatusCode.NoContent, "", req => // 204 No Content for DELETE
        {
            req.Method.Should().Be(HttpMethod.Delete);
            req.RequestUri.AbsolutePath.Should().Be($"{ApiPathPrefix}/guilds/{guildId}/items/{itemId}");
            requestValidated = true;
        }));

        await client.DeleteStoreItemAsync(guildId, itemId);
        requestValidated.Should().BeTrue();
    }

    // TODO: Add more tests for GetStoreItemAsync, EditStoreItemAsync, and GetStoreItemsAsync with options.

    public void Dispose() => _mockHttpClient?.Dispose();
}
